### ISSUE TITLE
Can you add build instructions?

### ISSUE THREAD

**Issue by salazarbarrera** [n0Live/BrickGame#1]
Hi! Sorry to bother, I know this is an unmaintained and very old repo, but do you know if it is still possible to buid the project? And if the answer is yes, how?

I've been trying to do it via command line, eclipse, javafx scenebuilder, and nothing. I just can't understand how to build the it. Can you add the requirements to the Readme? Not even full instruction, just what IDE and which JDK version is recommended.

Thanks in advanced!

**Comment by n0Live** [comment]
Hi! Just use an actual version of Eclipse to build this project. You will also need to add javafx.media.jar (from https://openjfx.io) to the project build path.
If Eclipse shows you a bunch of errors on settings.xml, just ignore them.

**Comment by salazarbarrera** [comment]
Thanks! I could finally build it.

Downloading Openjfx and letting Eclipse to handle the paths did the trick.

It crashes when it runs because I still need to remove references to JXInput in order to make it work under linux, but the jar is being built successfully.

**Comment by salazarbarrera** [comment]
solved (I also could run it, I deleted references to jxInput and used the command `$ java --module-path ./ext-lib/javafx-sdk --add-modules javafx.media -jar BrickGame.jar`, it worked perfectly )
